flaskapp:
  build: ./
  working_dir: /var/www/app
  command: bash -c "supervisord -c /etc/supervisord.conf"
  volumes:
    - ./app:/var/www/app:rw
    - ./app/log:/var/www/app/log:rw
    - ./supervisor/supervisord.conf:/etc/supervisord.conf:ro
    - ./supervisor/conf.d:/etc/supervisor/conf.d:ro
  links:
    - postgresql
    - rabbitmq
    - redis
  environment:
    - APP_ENVIRONMENT=PRODUCTION
    - FLASK_SETTINGS=settings/prod.py

postgresql:
  restart: always
  image: postgres:latest
  env_file: postgresql/.env
  volumes:
    - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata:rw
  ports:
    - "5432"

rabbitmq:
  restart: always
  image: rabbitmq:latest
  env_file: rabbitmq/.env
  ports:
    - "5672"

redis:
  restart: always
  image: redis:latest
  env_file: redis/.env
  volumes:
    - ./redis/redis.conf:/data/redis.conf:ro
  command: redis-server /data/redis.conf
  ports:
    - "6379"

nginx:
  restart: always
  image: nginx:latest
  env_file: nginx/.env
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/flask_app.conf:/etc/nginx/sites-enabled/flask_app.conf:ro
    - ./app/run/uwsgi:/var/run/uwsgi:ro
  ports:
    - "80:80"
