flaskapp:
  build: ./
  working_dir: /var/www/app
  command: bash -c "supervisord -c /etc/supervisord.conf"
  volumes:
    - ./app:/var/www/app:rw
    - ./supervisor/supervisord.conf:/etc/supervisord.conf:ro
    - ./supervisor/conf.d:/etc/supervisor/conf.d:ro
  links:
    - postgresql
  environment:
    - APP_ENVIRONMENT=DEVELOPMENT
    - FLASK_SETTINGS=settings/dev.py
  ports:
    - "5000:5000"

postgresql:
  restart: always
  image: postgres:latest
  env_file: postgresql/.env
  volumes:
    - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata:rw
  ports:
    - "5432"
