"""empty message

Revision ID: 4ff137d251b
Revises: 331b1da5f0e
Create Date: 2015-07-18 14:43:53.696985

"""

# revision identifiers, used by Alembic.
revision = '4ff137d251b'
down_revision = '331b1da5f0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('times', sa.Column('comment', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'comment')
    op.drop_column('attachments', 'comment')
    ### end Alembic commands ###
