"""empty message

Revision ID: 646ba6a7c3
Revises: 33a6fd474bf
Create Date: 2015-06-30 14:48:53.199875

"""

# revision identifiers, used by Alembic.
revision = '646ba6a7c3'
down_revision = '33a6fd474bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.add_column('tasks', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('tasks', 'updated')
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###
